INPUT:
  NAME: "mini_imagenet"
  DATA_DIR: "../Datasets/split_mini_imagenet"
  SIZE_TRAIN: 224
  SIZE_TEST: 224
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

MODEL:
  MODEL_NAME: "resnet"
  NUM_CLASSES: 100
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 2

TEST:
  IMS_PER_BATCH: 2

OUTPUT_DIR: "./outputs/mini_imagenet"